name: Staging Docker Image

on:
  push:
    branches:
      - STAGING

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: 'true'  # Ensures submodules are initialized and updated

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/econlabs/econlabs/fsdc-api:staging
